import { CompliancePack } from '@ai-governance/types';

export const gdprPack: CompliancePack = {
  framework: 'gdpr',
  name: 'GDPR (EU General Data Protection Regulation)',
  version: '2018',
  description:
    'GDPR compliance for AI systems processing EU personal data. Enforces data minimization, purpose limitation, and individual rights.',
  category: 'Privacy & Data Protection',
  controls: [
    {
      controlId: 'GDPR-ART5-1C',
      framework: 'gdpr',
      title: 'Data Minimization',
      description: 'Personal data in AI prompts is minimized — only data necessary for the task is permitted.',
      severity: 'critical',
      policyRuleType: 'pii_detection',
      automatable: true,
      mappedRuleIds: ['rule_pii_masking', 'rule_data_minimization'],
    },
    {
      controlId: 'GDPR-ART5-1E',
      framework: 'gdpr',
      title: 'Storage Limitation',
      description: 'Prompt and response logs containing personal data are retained only as long as necessary.',
      severity: 'high',
      policyRuleType: 'data_retention',
      automatable: true,
      mappedRuleIds: ['rule_log_retention_90d'],
    },
    {
      controlId: 'GDPR-ART25',
      framework: 'gdpr',
      title: 'Privacy by Design',
      description: 'PII masking is applied by default to all AI requests — opt-out requires explicit justification.',
      severity: 'critical',
      policyRuleType: 'pii_detection',
      automatable: true,
      mappedRuleIds: ['rule_pii_masking'],
    },
    {
      controlId: 'GDPR-ART32',
      framework: 'gdpr',
      title: 'Security of Processing',
      description: 'All AI interactions are encrypted at rest and in transit. Access is logged.',
      severity: 'critical',
      policyRuleType: 'encryption',
      automatable: true,
      mappedRuleIds: ['rule_tls_enforcement', 'rule_audit_all_requests'],
    },
    {
      controlId: 'GDPR-ART44',
      framework: 'gdpr',
      title: 'Data Transfer Restrictions',
      description: 'Personal data must not be sent to AI providers outside the EU without adequate safeguards.',
      severity: 'critical',
      policyRuleType: 'region_restriction',
      automatable: true,
      mappedRuleIds: ['rule_eu_data_residency'],
    },
    {
      controlId: 'GDPR-ART17',
      framework: 'gdpr',
      title: 'Right to Erasure Logging',
      description: 'Requests involving personal data are flagged to support right-to-erasure workflows.',
      severity: 'high',
      policyRuleType: 'audit_logging',
      automatable: true,
      mappedRuleIds: ['rule_erasure_flag'],
    },
  ],
  requiredRules: ['rule_pii_masking', 'rule_eu_data_residency', 'rule_audit_all_requests', 'rule_log_retention_90d'],
  recommendedRules: ['rule_data_minimization', 'rule_erasure_flag', 'rule_tls_enforcement'],
};
