import { CompliancePack } from '@ai-governance/types';

export const hipaaPack: CompliancePack = {
  framework: 'hipaa',
  name: 'HIPAA (Health Insurance Portability and Accountability Act)',
  version: '2013-omnibus',
  description:
    'HIPAA Security and Privacy Rules for AI systems that process Protected Health Information (PHI). Requires BAA with AI providers.',
  category: 'Healthcare Compliance',
  controls: [
    {
      controlId: 'HIPAA-164.312-A1',
      framework: 'hipaa',
      title: 'PHI Detection & Blocking',
      description: 'Protected Health Information (names, DOB, diagnosis, MRN) is detected and blocked from AI prompts.',
      severity: 'critical',
      policyRuleType: 'pii_detection',
      automatable: true,
      mappedRuleIds: ['rule_phi_detection', 'rule_pii_masking'],
    },
    {
      controlId: 'HIPAA-164.312-B',
      framework: 'hipaa',
      title: 'Audit Controls',
      description: 'All access to AI systems processing PHI is logged with user identity and timestamp.',
      severity: 'critical',
      policyRuleType: 'audit_logging',
      automatable: true,
      mappedRuleIds: ['rule_audit_all_requests'],
    },
    {
      controlId: 'HIPAA-164.312-C1',
      framework: 'hipaa',
      title: 'Data Integrity',
      description: 'AI responses are verified not to introduce or alter clinical information.',
      severity: 'high',
      policyRuleType: 'response_filter',
      automatable: true,
      mappedRuleIds: ['rule_response_integrity'],
    },
    {
      controlId: 'HIPAA-164.312-E1',
      framework: 'hipaa',
      title: 'Transmission Security',
      description: 'PHI transmitted to AI providers is encrypted. Only HIPAA BAA-covered providers are permitted.',
      severity: 'critical',
      policyRuleType: 'model_restriction',
      automatable: true,
      mappedRuleIds: ['rule_hipaa_approved_providers'],
    },
    {
      controlId: 'HIPAA-164.308-A3',
      framework: 'hipaa',
      title: 'Workforce Access Controls',
      description: 'Only authorized clinical staff may use AI features that process PHI.',
      severity: 'critical',
      policyRuleType: 'access_control',
      automatable: true,
      mappedRuleIds: ['rule_auth_required', 'rule_role_enforcement'],
    },
    {
      controlId: 'HIPAA-164.308-A6',
      framework: 'hipaa',
      title: 'Security Incident Procedures',
      description: 'PHI exposure incidents via AI are automatically flagged and escalated.',
      severity: 'critical',
      policyRuleType: 'audit_logging',
      automatable: true,
      mappedRuleIds: ['rule_phi_incident_alert'],
    },
  ],
  requiredRules: [
    'rule_phi_detection', 'rule_pii_masking', 'rule_audit_all_requests',
    'rule_hipaa_approved_providers', 'rule_auth_required',
  ],
  recommendedRules: ['rule_response_integrity', 'rule_role_enforcement', 'rule_phi_incident_alert'],
};
