import { CompliancePack } from '@ai-governance/types';

export const iso42001Pack: CompliancePack = {
  framework: 'iso-42001',
  name: 'ISO/IEC 42001 — AI Management System',
  version: '2023',
  description:
    'ISO 42001 is the international standard for AI Management Systems. It provides requirements for responsible development, deployment, and use of AI.',
  category: 'AI Governance',
  controls: [
    {
      controlId: 'ISO42001-6.1',
      framework: 'iso-42001',
      title: 'AI Risk Assessment',
      description: 'Risks associated with AI use are identified, assessed, and treated systematically.',
      severity: 'high',
      policyRuleType: 'data_classification',
      automatable: true,
      mappedRuleIds: ['rule_risk_scoring'],
    },
    {
      controlId: 'ISO42001-8.4',
      framework: 'iso-42001',
      title: 'AI System Documentation',
      description: 'All AI models in use are documented including purpose, provider, and risk level.',
      severity: 'medium',
      policyRuleType: 'model_restriction',
      automatable: true,
      mappedRuleIds: ['rule_model_allowlist'],
    },
    {
      controlId: 'ISO42001-8.5',
      framework: 'iso-42001',
      title: 'Human Oversight',
      description: 'High-risk AI decisions are flagged for human review before action is taken.',
      severity: 'high',
      policyRuleType: 'data_classification',
      automatable: true,
      mappedRuleIds: ['rule_high_risk_flag'],
    },
    {
      controlId: 'ISO42001-9.1',
      framework: 'iso-42001',
      title: 'Performance Monitoring',
      description: 'AI system performance, usage, and policy compliance are continuously monitored.',
      severity: 'medium',
      policyRuleType: 'audit_logging',
      automatable: true,
      mappedRuleIds: ['rule_audit_all_requests'],
    },
    {
      controlId: 'ISO42001-10.1',
      framework: 'iso-42001',
      title: 'Continual Improvement',
      description: 'Policy violations and incidents are reviewed to improve AI governance controls.',
      severity: 'low',
      policyRuleType: 'audit_logging',
      automatable: false,
      mappedRuleIds: ['rule_audit_violations'],
    },
  ],
  requiredRules: ['rule_model_allowlist', 'rule_audit_all_requests', 'rule_risk_scoring'],
  recommendedRules: ['rule_high_risk_flag', 'rule_audit_violations'],
};
