import { CompliancePack } from '@ai-governance/types';

export const nistAiRmfPack: CompliancePack = {
  framework: 'nist-ai-rmf',
  name: 'NIST AI Risk Management Framework',
  version: '1.0',
  description:
    'NIST AI RMF provides a structured approach to managing risks associated with AI systems across four core functions: GOVERN, MAP, MEASURE, and MANAGE.',
  category: 'AI Risk Management',
  controls: [
    {
      controlId: 'NIST-GOVERN-1.1',
      framework: 'nist-ai-rmf',
      title: 'AI Risk Policy Documentation',
      description: 'Policies and procedures for AI risk management are established and communicated.',
      severity: 'high',
      policyRuleType: 'audit_logging',
      automatable: true,
      mappedRuleIds: ['rule_audit_all_requests'],
    },
    {
      controlId: 'NIST-GOVERN-1.2',
      framework: 'nist-ai-rmf',
      title: 'Approved Model Inventory',
      description: 'Only approved AI models may be used. Unapproved models are blocked.',
      severity: 'critical',
      policyRuleType: 'model_restriction',
      automatable: true,
      mappedRuleIds: ['rule_model_allowlist'],
    },
    {
      controlId: 'NIST-MAP-1.1',
      framework: 'nist-ai-rmf',
      title: 'Prompt Risk Scoring',
      description: 'All prompts are evaluated for risk before being sent to AI providers.',
      severity: 'high',
      policyRuleType: 'data_classification',
      automatable: true,
      mappedRuleIds: ['rule_risk_scoring'],
    },
    {
      controlId: 'NIST-MEASURE-2.1',
      framework: 'nist-ai-rmf',
      title: 'Bias & Harmful Content Detection',
      description: 'Prompts and responses are scanned for harmful, biased, or unsafe content.',
      severity: 'high',
      policyRuleType: 'keyword_block',
      automatable: true,
      mappedRuleIds: ['rule_harmful_content'],
    },
    {
      controlId: 'NIST-MANAGE-1.1',
      framework: 'nist-ai-rmf',
      title: 'Incident Response Logging',
      description: 'All policy violations are logged with full context for incident response.',
      severity: 'critical',
      policyRuleType: 'audit_logging',
      automatable: true,
      mappedRuleIds: ['rule_audit_violations'],
    },
    {
      controlId: 'NIST-MANAGE-2.1',
      framework: 'nist-ai-rmf',
      title: 'Cost & Usage Monitoring',
      description: 'AI usage and costs are tracked per team to detect anomalous consumption.',
      severity: 'medium',
      policyRuleType: 'cost_limit',
      automatable: true,
      mappedRuleIds: ['rule_cost_alert'],
    },
  ],
  requiredRules: ['rule_audit_all_requests', 'rule_model_allowlist', 'rule_audit_violations'],
  recommendedRules: ['rule_risk_scoring', 'rule_harmful_content', 'rule_cost_alert'],
};
