import { CompliancePack } from '@ai-governance/types';

export const pipedaPack: CompliancePack = {
  framework: 'pipeda',
  name: 'PIPEDA (Canadian Privacy Law)',
  version: '2019',
  description:
    'Canada\'s Personal Information Protection and Electronic Documents Act. Governs how private sector organizations collect, use, and disclose personal information in AI systems.',
  category: 'Privacy & Data Protection',
  controls: [
    {
      controlId: 'PIPEDA-P1',
      framework: 'pipeda',
      title: 'Accountability',
      description: 'Organization is accountable for personal information in AI prompts and responses.',
      severity: 'high',
      policyRuleType: 'audit_logging',
      automatable: true,
      mappedRuleIds: ['rule_audit_all_requests'],
    },
    {
      controlId: 'PIPEDA-P4',
      framework: 'pipeda',
      title: 'Limiting Collection',
      description: 'Personal information sent to AI is limited to what is necessary for the identified purpose.',
      severity: 'critical',
      policyRuleType: 'pii_detection',
      automatable: true,
      mappedRuleIds: ['rule_pii_masking', 'rule_data_minimization'],
    },
    {
      controlId: 'PIPEDA-P7',
      framework: 'pipeda',
      title: 'Safeguards',
      description: 'Personal information in AI interactions is protected by security safeguards appropriate to sensitivity.',
      severity: 'critical',
      policyRuleType: 'encryption',
      automatable: true,
      mappedRuleIds: ['rule_tls_enforcement', 'rule_audit_all_requests'],
    },
    {
      controlId: 'PIPEDA-P8',
      framework: 'pipeda',
      title: 'Openness',
      description: 'Employees are informed that AI usage is monitored for compliance purposes.',
      severity: 'medium',
      policyRuleType: 'audit_logging',
      automatable: false,
      mappedRuleIds: [],
    },
    {
      controlId: 'PIPEDA-P9',
      framework: 'pipeda',
      title: 'Individual Access',
      description: 'Individuals can request access to their AI interaction logs.',
      severity: 'medium',
      policyRuleType: 'audit_logging',
      automatable: true,
      mappedRuleIds: ['rule_audit_all_requests'],
    },
  ],
  requiredRules: ['rule_pii_masking', 'rule_audit_all_requests', 'rule_tls_enforcement'],
  recommendedRules: ['rule_data_minimization', 'rule_log_retention_90d'],
};
