import { CompliancePack } from '@ai-governance/types';

export const soc2Pack: CompliancePack = {
  framework: 'soc2',
  name: 'SOC 2 Type II',
  version: '2017',
  description:
    'SOC 2 Trust Services Criteria covering Security, Availability, Processing Integrity, Confidentiality, and Privacy for AI systems.',
  category: 'Security & Audit',
  controls: [
    {
      controlId: 'SOC2-CC6.1',
      framework: 'soc2',
      title: 'Logical Access Controls',
      description: 'Access to AI systems is restricted to authorized users via API keys and tenant isolation.',
      severity: 'critical',
      policyRuleType: 'access_control',
      automatable: true,
      mappedRuleIds: ['rule_auth_required'],
    },
    {
      controlId: 'SOC2-CC6.7',
      framework: 'soc2',
      title: 'Data Transmission Encryption',
      description: 'All data transmitted to and from AI providers is encrypted in transit (TLS 1.3).',
      severity: 'critical',
      policyRuleType: 'encryption',
      automatable: true,
      mappedRuleIds: ['rule_tls_enforcement'],
    },
    {
      controlId: 'SOC2-CC7.2',
      framework: 'soc2',
      title: 'Anomaly & Threat Detection',
      description: 'Unusual AI usage patterns trigger alerts for security review.',
      severity: 'high',
      policyRuleType: 'rate_limit',
      automatable: true,
      mappedRuleIds: ['rule_anomaly_detection'],
    },
    {
      controlId: 'SOC2-CC9.1',
      framework: 'soc2',
      title: 'Vendor Risk Management',
      description: 'Only approved AI vendors (Bedrock, OpenAI) may be used. New vendors require review.',
      severity: 'high',
      policyRuleType: 'model_restriction',
      automatable: true,
      mappedRuleIds: ['rule_approved_providers'],
    },
    {
      controlId: 'SOC2-P3.1',
      framework: 'soc2',
      title: 'Sensitive Data in AI Prompts',
      description: 'Confidential data is detected and masked before being sent to external AI providers.',
      severity: 'critical',
      policyRuleType: 'pii_detection',
      automatable: true,
      mappedRuleIds: ['rule_pii_masking', 'rule_confidential_data'],
    },
    {
      controlId: 'SOC2-A1.1',
      framework: 'soc2',
      title: 'Availability & Rate Limiting',
      description: 'Rate limits prevent abuse and ensure AI services remain available to all users.',
      severity: 'medium',
      policyRuleType: 'rate_limit',
      automatable: true,
      mappedRuleIds: ['rule_rate_limit'],
    },
  ],
  requiredRules: ['rule_auth_required', 'rule_pii_masking', 'rule_approved_providers', 'rule_audit_all_requests'],
  recommendedRules: ['rule_anomaly_detection', 'rule_rate_limit', 'rule_confidential_data'],
};
