export const mockTenants = [
  {
    tenantId: 'tenant_demo',
    name: 'Demo Corp',
    plan: 'professional',
    status: 'active',
    deploymentMode: 'saas',
    region: 'us-east-1',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-01T00:00:00Z',
    adminEmail: 'admin@democorp.com',
    usageThisMonth: { requests: 12847, cost: 48.32, violations: 234 },
    settings: {
      allowedModels: ['anthropic.claude-3-haiku-20240307-v1:0', 'anthropic.claude-3-sonnet-20240229-v1:0'],
      maxTokensPerRequest: 4096,
      maxRequestsPerMinute: 100,
      dataResidencyRegion: 'us-east-1',
      piiMaskingEnabled: true,
      auditLogRetentionDays: 365,
      allowExternalProviders: true,
    },
  },
  {
    tenantId: 'tenant_healthco',
    name: 'HealthCo Systems',
    plan: 'enterprise',
    status: 'active',
    deploymentMode: 'onprem',
    region: 'us-east-1',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-03-15T00:00:00Z',
    adminEmail: 'it@healthco.com',
    usageThisMonth: { requests: 45200, cost: 312.80, violations: 12 },
    settings: {
      allowedModels: ['anthropic.claude-3-haiku-20240307-v1:0'],
      maxTokensPerRequest: 2048,
      maxRequestsPerMinute: 200,
      dataResidencyRegion: 'us-east-1',
      piiMaskingEnabled: true,
      auditLogRetentionDays: 2555,
      allowExternalProviders: false,
    },
  },
  {
    tenantId: 'tenant_fintech',
    name: 'FinTech Innovations',
    plan: 'starter',
    status: 'trial',
    deploymentMode: 'saas',
    region: 'ca-central-1',
    createdAt: '2026-03-20T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z',
    adminEmail: 'dev@fintech.io',
    usageThisMonth: { requests: 1240, cost: 4.20, violations: 3 },
    settings: {
      allowedModels: ['anthropic.claude-3-haiku-20240307-v1:0'],
      maxTokensPerRequest: 4096,
      maxRequestsPerMinute: 60,
      dataResidencyRegion: 'ca-central-1',
      piiMaskingEnabled: true,
      auditLogRetentionDays: 90,
      allowExternalProviders: false,
    },
  },
  {
    tenantId: 'tenant_legalfirm',
    name: 'Morrison & Associates',
    plan: 'professional',
    status: 'suspended',
    deploymentMode: 'saas',
    region: 'us-east-1',
    createdAt: '2025-11-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
    adminEmail: 'admin@morrison.law',
    usageThisMonth: { requests: 0, cost: 0, violations: 0 },
    settings: {
      allowedModels: [],
      maxTokensPerRequest: 4096,
      maxRequestsPerMinute: 100,
      dataResidencyRegion: 'us-east-1',
      piiMaskingEnabled: true,
      auditLogRetentionDays: 365,
      allowExternalProviders: false,
    },
  },
];
