// Mock data used when backend is unavailable or for Storybook/tests

export const mockSummary = {
  totalRequests: 12847,
  blockedRequests: 234,
  totalCost: 48.32,
  piiDetectionCount: 89,
  avgLatencyMs: 312,
  requestsTrend: [
    { date: '03-24', requests: 1420, blocked: 28 },
    { date: '03-25', requests: 1890, blocked: 41 },
    { date: '03-26', requests: 1650, blocked: 19 },
    { date: '03-27', requests: 2100, blocked: 55 },
    { date: '03-28', requests: 1780, blocked: 32 },
    { date: '03-29', requests: 2340, blocked: 38 },
    { date: '03-30', requests: 1667, blocked: 21 },
  ],
  costTrend: [
    { date: '03-24', cost: 5.2 },
    { date: '03-25', cost: 7.8 },
    { date: '03-26', cost: 6.1 },
    { date: '03-27', cost: 9.4 },
    { date: '03-28', cost: 7.2 },
    { date: '03-29', cost: 8.9 },
    { date: '03-30', cost: 3.72 },
  ],
};

export const mockModelDistribution = [
  { name: 'Claude 3 Haiku', value: 48, color: '#6366f1' },
  { name: 'Claude 3 Sonnet', value: 28, color: '#818cf8' },
  { name: 'GPT-4o', value: 16, color: '#34d399' },
  { name: 'Titan Express', value: 8, color: '#94a3b8' },
];

export const mockAuditLogs = Array.from({ length: 20 }, (_, i) => ({
  logId: `log_${i + 1}`,
  requestId: `req_${Math.random().toString(36).slice(2, 10)}`,
  userId: `user_${(i % 5) + 1}`,
  appId: `app_${(i % 3) + 1}`,
  modelId: ['anthropic.claude-3-haiku', 'gpt-4o', 'anthropic.claude-3-sonnet'][i % 3],
  provider: ['bedrock', 'openai', 'bedrock'][i % 3],
  policyDecision: i % 8 === 0 ? 'block' : 'allow',
  piiDetected: i % 6 === 0,
  inputTokens: Math.floor(Math.random() * 800) + 100,
  outputTokens: Math.floor(Math.random() * 400) + 50,
  estimatedCost: parseFloat((Math.random() * 0.02).toFixed(4)),
  latencyMs: Math.floor(Math.random() * 800) + 100,
  timestamp: new Date(Date.now() - i * 3_600_000).toISOString(),
}));

export const mockModelConfigs = [
  {
    modelConfigId: 'model_claude_haiku',
    tenantId: 'tenant_demo',
    name: 'Claude 3 Haiku (Fast)',
    provider: 'bedrock',
    modelId: 'anthropic.claude-3-haiku-20240307-v1:0',
    status: 'active',
    isDefault: true,
    region: 'us-east-1',
    maxTokensPerRequest: 4096,
    maxContextTokens: 200000,
    inputCostPer1kTokens: 0.00025,
    outputCostPer1kTokens: 0.00125,
    allowedForRoles: [],
    allowedForApps: [],
    requiresApproval: false,
    tags: ['fast', 'cost-effective'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    createdBy: 'admin',
    lastTestedAt: '2026-03-30T10:00:00Z',
    lastTestStatus: 'pass',
  },
  {
    modelConfigId: 'model_claude_sonnet',
    tenantId: 'tenant_demo',
    name: 'Claude 3 Sonnet (Balanced)',
    provider: 'bedrock',
    modelId: 'anthropic.claude-3-sonnet-20240229-v1:0',
    status: 'active',
    isDefault: false,
    region: 'us-east-1',
    maxTokensPerRequest: 4096,
    maxContextTokens: 200000,
    inputCostPer1kTokens: 0.003,
    outputCostPer1kTokens: 0.015,
    allowedForRoles: [],
    allowedForApps: [],
    requiresApproval: false,
    tags: ['balanced'],
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    createdBy: 'admin',
    lastTestedAt: '2026-03-29T14:00:00Z',
    lastTestStatus: 'pass',
  },
  {
    modelConfigId: 'model_gpt4o',
    tenantId: 'tenant_demo',
    name: 'GPT-4o (OpenAI)',
    provider: 'openai',
    modelId: 'gpt-4o',
    status: 'testing',
    isDefault: false,
    apiKeyHint: '...k3f9',
    maxTokensPerRequest: 4096,
    maxContextTokens: 128000,
    inputCostPer1kTokens: 0.005,
    outputCostPer1kTokens: 0.015,
    allowedForRoles: ['admin', 'developer'],
    allowedForApps: [],
    requiresApproval: true,
    tags: ['powerful', 'vision'],
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
    createdBy: 'admin',
    lastTestStatus: 'fail',
  },
];

export const mockPolicies = [
  {
    policyId: 'policy_default',
    tenantId: 'tenant_demo',
    name: 'Default Policy',
    description: 'Block sensitive keywords',
    enabled: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    createdBy: 'admin',
    rules: [
      {
        ruleId: 'rule_keywords',
        type: 'keyword_block',
        action: 'block',
        priority: 1,
        enabled: true,
        description: 'Block confidential keywords',
        config: { keywords: ['confidential', 'top secret', 'internal only'] },
      },
    ],
  },
  {
    policyId: 'policy_pii',
    tenantId: 'tenant_demo',
    name: 'PII Protection',
    description: 'Detect and mask PII in all requests',
    enabled: true,
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-01-15T00:00:00Z',
    createdBy: 'admin',
    rules: [
      {
        ruleId: 'rule_pii',
        type: 'pii_detection',
        action: 'mask',
        priority: 1,
        enabled: true,
        description: 'Mask PII before sending to AI',
        config: {},
      },
    ],
  },
];
