export const mockCompliancePacks = [
  {
    framework: 'nist-ai-rmf',
    name: 'NIST AI Risk Management Framework',
    version: '1.0',
    description: 'Structured approach to managing AI risks across GOVERN, MAP, MEASURE, and MANAGE functions.',
    category: 'AI Risk Management',
    status: 'disabled',
    passedControls: 0,
    totalControls: 6,
    controls: [
      { controlId: 'NIST-GOVERN-1.1', title: 'AI Risk Policy Documentation', severity: 'high', automatable: true },
      { controlId: 'NIST-GOVERN-1.2', title: 'Approved Model Inventory', severity: 'critical', automatable: true },
      { controlId: 'NIST-MAP-1.1', title: 'Prompt Risk Scoring', severity: 'high', automatable: true },
      { controlId: 'NIST-MEASURE-2.1', title: 'Bias & Harmful Content Detection', severity: 'high', automatable: true },
      { controlId: 'NIST-MANAGE-1.1', title: 'Incident Response Logging', severity: 'critical', automatable: true },
      { controlId: 'NIST-MANAGE-2.1', title: 'Cost & Usage Monitoring', severity: 'medium', automatable: true },
    ],
  },
  {
    framework: 'soc2',
    name: 'SOC 2 Type II',
    version: '2017',
    description: 'Trust Services Criteria covering Security, Availability, Confidentiality, and Privacy.',
    category: 'Security & Audit',
    status: 'enabled',
    passedControls: 4,
    totalControls: 6,
    controls: [
      { controlId: 'SOC2-CC6.1', title: 'Logical Access Controls', severity: 'critical', automatable: true },
      { controlId: 'SOC2-CC6.7', title: 'Data Transmission Encryption', severity: 'critical', automatable: true },
      { controlId: 'SOC2-CC7.2', title: 'Anomaly & Threat Detection', severity: 'high', automatable: true },
      { controlId: 'SOC2-CC9.1', title: 'Vendor Risk Management', severity: 'high', automatable: true },
      { controlId: 'SOC2-P3.1', title: 'Sensitive Data in AI Prompts', severity: 'critical', automatable: true },
      { controlId: 'SOC2-A1.1', title: 'Availability & Rate Limiting', severity: 'medium', automatable: true },
    ],
  },
  {
    framework: 'gdpr',
    name: 'GDPR',
    version: '2018',
    description: 'EU General Data Protection Regulation for AI systems processing personal data.',
    category: 'Privacy & Data Protection',
    status: 'partial',
    passedControls: 3,
    totalControls: 6,
    controls: [
      { controlId: 'GDPR-ART5-1C', title: 'Data Minimization', severity: 'critical', automatable: true },
      { controlId: 'GDPR-ART5-1E', title: 'Storage Limitation', severity: 'high', automatable: true },
      { controlId: 'GDPR-ART25', title: 'Privacy by Design', severity: 'critical', automatable: true },
      { controlId: 'GDPR-ART32', title: 'Security of Processing', severity: 'critical', automatable: true },
      { controlId: 'GDPR-ART44', title: 'Data Transfer Restrictions', severity: 'critical', automatable: true },
      { controlId: 'GDPR-ART17', title: 'Right to Erasure Logging', severity: 'high', automatable: true },
    ],
  },
  {
    framework: 'hipaa',
    name: 'HIPAA',
    version: '2013-omnibus',
    description: 'Health Insurance Portability and Accountability Act for AI systems processing PHI.',
    category: 'Healthcare Compliance',
    status: 'disabled',
    passedControls: 0,
    totalControls: 6,
    controls: [
      { controlId: 'HIPAA-164.312-A1', title: 'PHI Detection & Blocking', severity: 'critical', automatable: true },
      { controlId: 'HIPAA-164.312-B', title: 'Audit Controls', severity: 'critical', automatable: true },
      { controlId: 'HIPAA-164.312-C1', title: 'Data Integrity', severity: 'high', automatable: true },
      { controlId: 'HIPAA-164.312-E1', title: 'Transmission Security', severity: 'critical', automatable: true },
      { controlId: 'HIPAA-164.308-A3', title: 'Workforce Access Controls', severity: 'critical', automatable: true },
      { controlId: 'HIPAA-164.308-A6', title: 'Security Incident Procedures', severity: 'critical', automatable: true },
    ],
  },
  {
    framework: 'iso-42001',
    name: 'ISO/IEC 42001',
    version: '2023',
    description: 'International standard for AI Management Systems — responsible AI development and deployment.',
    category: 'AI Governance',
    status: 'disabled',
    passedControls: 0,
    totalControls: 5,
    controls: [
      { controlId: 'ISO42001-6.1', title: 'AI Risk Assessment', severity: 'high', automatable: true },
      { controlId: 'ISO42001-8.4', title: 'AI System Documentation', severity: 'medium', automatable: true },
      { controlId: 'ISO42001-8.5', title: 'Human Oversight', severity: 'high', automatable: true },
      { controlId: 'ISO42001-9.1', title: 'Performance Monitoring', severity: 'medium', automatable: true },
      { controlId: 'ISO42001-10.1', title: 'Continual Improvement', severity: 'low', automatable: false },
    ],
  },
  {
    framework: 'pipeda',
    name: 'PIPEDA',
    version: '2019',
    description: "Canada's Personal Information Protection and Electronic Documents Act.",
    category: 'Privacy & Data Protection',
    status: 'disabled',
    passedControls: 0,
    totalControls: 5,
    controls: [
      { controlId: 'PIPEDA-P1', title: 'Accountability', severity: 'high', automatable: true },
      { controlId: 'PIPEDA-P4', title: 'Limiting Collection', severity: 'critical', automatable: true },
      { controlId: 'PIPEDA-P7', title: 'Safeguards', severity: 'critical', automatable: true },
      { controlId: 'PIPEDA-P8', title: 'Openness', severity: 'medium', automatable: false },
      { controlId: 'PIPEDA-P9', title: 'Individual Access', severity: 'medium', automatable: true },
    ],
  },
];
